/*
 * BLE_MESSAGE_MANAGER.h
 *
 *  Created on: 29 Oct 2018
 *      Author: Adrien Mallet
 */

// ************** TCU COMMANDS
// BLE PART
#ifndef __BLE_PROF_DATA_CMDS_H
#define __BLE_PROF_DATA_CMDS_H

// SPP PART
/*
const uint8_t TCU_MNG_INIT_REQ2[15] = {0x0F, 0x00, 0x00, 0xE1, 0x01, 0x08, 0x00, 0x04, 0x02, 0x05, 0x42, 0x54, 0x53, 0x50, 0x50};
const uint8_t TCU_SPP_SETUP_REQ[7] = {0x07, 0x00, 0x00, 0xE5, 0x01, 0x00, 0x00};
const uint8_t TCU_MNG_SET_SCAN_REQ[8] = {0x08, 0x00, 0x00, 0xE1, 0x0C, 0x01, 0x00, 0x03};
 * */

// END TCU COMMANDS

// Device Information Characteristics
#define SPPOBLE_CHAR_HANDLE_VALUE 0x0211                // 
#define DEVICE_NAME_CHAR_HANDLE_VALUE 0x0011            // 
#define MANUFACTURER_NAME_CHAR_HANDLE_VALUE 0x0111      //= (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ2[8] << 8 | TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ2[7] + 0x01)   //0x0111
#define MODEL_NUMBER_CHAR_HANDLE_VALUE 0x0121           //= (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ3[8] << 8 | TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ3[7] + 0x01)   //0x0121
#define SYSTEM_ID_CHAR_HANDLE_VALUE 0x0131              //= (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ4[8] << 8 | TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ4[7] + 0x01)   //0x0131
#define HARDWARE_REVISION_CHAR_HANDLE_VALUE 0x0141      //= (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ5[8] << 8 | TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ5[7] + 0x01)   //0x0141

#define ADVERTISEMENT_DATA_CHAR_DATA_LENGTH (54)
#define ADVERTISEMENT_DATA_CHAR_CUSTOM_DATA_START_INDEX (62)

#define BD_ADDRESS_CHAR_DATA_LENGTH (TCU_HCI_WRITE_BD_ADDR_REQ[3])
#define BD_ADDRESS_CHAR_DATA_START_INDEX (TCU_HCI_WRITE_BD_ADDR_REQ[4])

#define SYSTEM_ID_CHAR_DATA_LENGTH (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ4[12])

#define SYSTEM_ID_CHAR_DATA_START_INDEX (14)

#define HARDWARE_REVISION_CHAR_DATA_LENGTH (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ5[12])
#define HARDWARE_REVISION_CHAR_DATA_START_INDEX (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ5[14])

#define MANUFACTURER_NAME_CHAR_DATA_LENGTH (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ2[12])
#define MANUFACTURER_NAME_CHAR_DATA_START_INDEX (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ2[14])

#define MODEL_NUMBER_CHAR_DATA_LENGTH (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ3[12])
#define MODEL_NUMBER_CHAR_DATA_START_INDEX (TCU_LE_GATT_SDB_ADD_CHAR_ELE_REQ3[14])

#define DEVICE_NAME_CHAR_DATA_LENGTH (TCU_LE_GATT_SDB_ADD_CHAR_VAR_ELE_REQ[14])
#define DEVICE_NAME_CHAR_DATA_START_INDEX (TCU_LE_GATT_SDB_ADD_CHAR_VAR_ELE_REQ[16])

#endif //__BLE_BIODY_PROFILE_DATA_CMDS_H_
